//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPractice1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string Address { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public string imagePath { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<Site> Sites { get; set; }
    }
}
